### PR TITLE
Master

### PR DESCRIPTION
**Pull request by gallopinggoose6**
A modification of the colors this is what I personally think is cool, but it can totally be changed, or these changes can be discarded, and I've turned all of the rows/columns of div s into links that can go to other pages, and I've given most of them labels, as a suggestion to a different direction in the design, however, if everybody hates my idea, you can discard the changes with no hard feelings. This is meant more as a suggestion than an actual substantial edit

### CODE REVIEW

**Comment by gallopinggoose6** [comment]
for some reason from my perspective on the website, it looks like GitHub messed with my message with the pull requests, so the random new line with an s at the beginning is supposed to be "I've turned all of the rows/columns of <div>s into links"
If you don't see anything strange, then ignore this comment.
P.S. I tried editing the message, but it just reverted back to what it was

**Comment by icyhydro** [comment]
Did you test it, and it works?

**Comment by gallopinggoose6** [comment]
I did test it, and it works, but you should have a look at it, purely because it's meant as a suggestion, also, let's talk on slack for a little bit, because I think we have a lot to say

**Comment by icyhydro** [comment]
Okay, let's talk on Slack.

**Pull request merged**
